apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-library-deployment
  labels:
    app: music-library
spec:
  replicas: 3
  selector:
    matchLabels:
      app: music-library
  template:
    metadata:
      labels:
        app: music-library
    spec:
      containers:
      - name: music-library
        image: 10.106.184.43/music-library:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: music-library-env
