apiVersion: v1
kind: ConfigMap
metadata:
  namespace: music-library
  name: music-library-env
  labels:
    app: music-library
data:
  FLASK_ENV: development
  MONGO_DB: Music-Library
  MONGO_HOST: mongo
  MONGO_PORT: "27017"
