apiVersion: v1
kind: Service
metadata:
  name: music-library-lb
  namespace: music-library
spec:
  selector:
    app: music-library
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
