apiVersion: v1
kind: Service
metadata:
  namespace: music-library
  name: music-library
spec:
  selector:
    app: music-library
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: music-library-port
    protocol: TCP
    port: 5002
    targetPort: 5002
